name: Zip Project Files

on:
  # Trigger manually from Actions tab
  workflow_dispatch:
  
  # Trigger on push to main branch
  push:
    branches:
      - main
  
  # Trigger on pull request
  pull_request:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT
      
      - name: Create zip archive
        run: |
          zip -r sanuflix-${{ steps.date.outputs.date }}.zip . \
            -x "*.git*" \
            -x "*node_modules/*" \
            -x "*dist/*" \
            -x "*build/*" \
            -x "*.next/*" \
            -x "*coverage/*" \
            -x "*.cache/*"
      
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: sanuflix-project-${{ steps.date.outputs.date }}
          path: sanuflix-*.zip
          retention-days: 30
      
      - name: Create Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: sanuflix-*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
